import initSoftScroll from "./modules/scroll-suave.js";
import initAnimacaoScroll from "./modules/anima-scroll.js";
import initTabNav from "./modules/tab-nav.js";
import initAccordion from "./modules/accordion-list.js";
import initModal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuMobile from "./modules/menu-mobile.js";
import initFuncionamento from "./modules/funcionamento.js";
import initFetchAnimais from "./modules/fetch-animais.js";
import initFetchBitcoin from "./modules/fetch-bitcoin.js";

initSoftScroll();
initAnimacaoScroll();
initTabNav();
initAccordion();
initModal();
initTooltip();
initDropdownMenu();
initMenuMobile();
initFuncionamento();
initFetchAnimais();
initFetchBitcoin();
